// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/27/2026, 8:23:11 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/huzaifah/workspace/portfolio/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/huzaifah/workspace/portfolio/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/huzaifah/workspace/portfolio/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/huzaifah/workspace/portfolio/app/plugins/**/*.{js,ts,mjs}","/home/huzaifah/workspace/portfolio/app/composables/**/*.{js,ts,mjs}","/home/huzaifah/workspace/portfolio/app/utils/**/*.{js,ts,mjs}","/home/huzaifah/workspace/portfolio/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/huzaifah/workspace/portfolio/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/huzaifah/workspace/portfolio/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/huzaifah/workspace/portfolio/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;