export const skillsConfig = {
  title: "Skills",
  skillsCategories: [
    {
      title: "Frontend",
      skills: [
        "TypeScript",
        "React",
        "Next.js",
        "Vue.js",
        "JavaScript",
        "HTML5",
        "CSS3",
        "TailwindCSS",
        "Redux",
        "Bootstrap"
      ],
    },
    {
      title: "Backend",
      skills: [
        "Go",
        "Java",
        "C++",
        "Python",
        "Node.js",
        "PostgreSQL",
        "Redis",
        "gRPC",
        "Protocol Buffers",
        "GraphQL",
        "MongoDB",
        "Django",
        "Express",
        "Elixir",
        "Erlang",
        "C"
      ],
    },
    {
      title: "DevOps",
      skills: [
        "Kubernetes",
        "Docker",
        "Terraform",
        "CI/CD",
        "GitHub Actions",
        "Helm",
        "ArgoCD",
        "Vault",
        "Consul",
        "Jenkins",
        "CDK",
        "CDKTF",
        "Fluentd",
        "Kibana",
        "GitLab",
        "Nginx",
        "DockerHub",
        "ArtifactHub",
        "Spinnaker"
      ],
    },
    {
      title: "Tools & Practices",
      skills: [
        "System Design",
        "Microservices",
        "REST APIs",
        "Git",
        "Automation",
        "Test-driven development",
        "Jest",
        "jUnit",
        "Mockito",
        "Scripting",
        "Bash",
        "Agile/Scrum",
        "Chromium",
        "Puppeteer",
        "Slack Bots",
        "Multiarch package builds"
      ],
    },
    {
      title: "AWS",
      skills: [
        "EKS",
        "Lambda",
        "EC2",
        "VPC",
        "IAM",
        "S3",
        "CloudWatch",
        "API Gateway",
        "ECS",
        "DynamoDB",
        "Aurora",
        "Kinesis",
        "MSK",
        "EventBridge",
        "CloudFormation",
        "Redshift",
        "Athena",
        "EMR",
        "ASG",
        "ELB",
        "CloudFront",
        "Route53",
        "Systems Manager",
        "CloudTrail",
        "KMS",
        "ACM",
        "Cognito",
        "SES",
        "SNS",
        "CodeBuild",
        "CodePipeline",
        "CodeDeploy",
        "CodeCommit",
        "Amplify",
        "EBS",
        "CLI"
      ],
    },
  ],
}
